---
kind: pipeline
type: docker
name: one-click-drone

steps:
  - name: cache key
    image: alpine
    commands:
      - touch .cache_key
      - echo -n $(md5sum package-lock.json)               >> .cache_key
      - echo -n $(cat .cache_key | md5sum | cut -c 1-32)  >  .cache_key

  - name: restore cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - node_modules

  - name: npm install
    image: node:alpine
    commands:
      - npm install --allow-root --unsafe-perm

  - name: npm install integrity
    image: alpine/git
    commands:
      - git diff --exit-code package-lock.json
      - git diff --exit-code package.json

  - name: npm run dist
    image: node:alpine
    commands:
      - npm run dist

  - name: push dist git
    image: alpine/git
    environment:
      GIT_USER:
        from_secret: github_deploy_user
      GIT_PASS:
        from_secret: github_deploy_pass
    commands:
      - git add dist/ocd.yml
      - git diff --staged --quiet || git commit -m "[skip ci] [dist push] updated raw CloudFormation file"
      - git remote add deploy "https://$GIT_USER:$GIT_PASS@github.com/$DRONE_REPO_OWNER/$DRONE_REPO_NAME.git"
      - git push deploy ${DRONE_COMMIT_BRANCH}

  - name: push dist s3
    image: sepehrl/one-click-drone
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_deploy_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_deploy_secret
    commands:
      - aws s3 cp dist/ocd.yml s3://one-click-drone
      - aws s3api put-object-acl --bucket one-click-drone --key ocd.yml --acl public-read
    when:
      branch:
        - master

  - name: rebuild cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    when:
      status:
        - success
        - failure
    settings:
      rebuild: true
      mount:
        - node_modules

volumes:
  - name: cache
    host:
      path: /mnt/efs
