version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    target_branch: 'develop'
    commit_message:
      prefix: '[NO CACHE]'
      include_scope: true
